name: "Create Scratch Org"

inputs:
  devHubOrgAuthUrl:
    description: "DevHub environment authorization URL"
    type: string
    required: true

  configFilePath:
    description: "Relative path to a scratch org configuration file"
    type: string
    default: "config/project-scratch-def.json"

  durationInDays:
    description: "Number of days for scratch org to expire after"
    required: true
    type: choice
    default: '5'
    options:
      - 1
      - 2
      - 3
      - 5
      - 7
      - 10
      - 15
      - 20
      - 30

outputs:
  scratchOrgUrl:
    description: "Login URL of the created scratch org"
    value: ${{ steps.createScratchOrg.outputs.scratchOrgUrl }}

  scratchOrgUsername:
    description: "Username of the created scratch org"
    value: ${{ steps.createScratchOrg.outputs.scratchOrgUsername }}

  scratchOrgPassword:
    description: "Password of the created scratch org"
    value: ${{ steps.createScratchOrg.outputs.scratchOrgPassword }}

  scratchOrgAuthUrl:
    description: "Authorization URL of the created scratch org"
    value: ${{ steps.getScratchOrgAuthUrl.outputs.scratchOrgAuthUrl }}

runs:
  using: "composite"

  steps:
    - name: "Authorize DevHub Org"
      id: authorizeDevHubOrg
      continue-on-error: false
      uses: ./.github/actions/authorizeOrg
      with:
        targetOrgAlias: "devHub"
        targetOrgAuthUrl: ${{ inputs.devHubOrgAuthUrl }}
      
    - name: "Create Scratch Org"
      id: createScratchOrg
      shell: bash
      continue-on-error: false
      env:
          SCRATCH_ORG_CONFIG_FILE_PATH: ${{ inputs.configFilePath }}
          SCRATCH_ORG_ALIAS: "scratchOrg"
          DEVHUB_ORG_ALIAS: ${{ steps.authorizeDevHubOrg.outputs.targetOrgAlias }}
      run: |
        echo "⏳ Creating a scratch org..."
        echo "Target scratch org configuration file: ${SCRATCH_ORG_CONFIG_FILE_PATH}"
        cat $SCRATCH_ORG_CONFIG_FILE_PATH

        # setting scratch org alias at runner's level for other steps. Declaring top-level 'env' attribute does not work for composite actions. 
        echo "SCRATCH_ORG_ALIAS=$SCRATCH_ORG_ALIAS" >> $GITHUB_ENV

    - name: "Get Scratch Org Authorization URL"
      id: getScratchOrgAuthUrl
      shell: bash
      run: |
        echo "⏳ Retrieving scratch org authorization URL..."

        SCRATCH_ORG_DETAILS=$(sf org display --target-org "$SCRATCH_ORG_ALIAS" --verbose --json)

        SCRATCH_ORG_DETAILS_STATUS_CODE=$(echo "$SCRATCH_ORG_DETAILS" | jq .status)

        # early exit - error when getting scratch org details
        if [[ "$SCRATCH_ORG_DETAILS_STATUS_CODE" != "0" ]]; then

          echo "❌ Problem when getting '$SCRATCH_ORG_ALIAS' scratch org details"
          exit 1

        fi

        SCRATCH_ORG_AUTH_URL=$(echo "$SCRATCH_ORG_DETAILS" | jq -r '.result.sfdxAuthUrl')

        # set scratch org authorization URL in output
        echo "scratchOrgAuthUrl=$SCRATCH_ORG_AUTH_URL" >> $GITHUB_OUTPUT

        echo "✅ Successfully retrieved '$SCRATCH_ORG_ALIAS' scratch org authorization URL"

    - name: "Set Profiles Login IP Ranges"
      shell: bash
      env:
        POST_STEP_PATH: "modules/common/scratch/01-meta-openAccess/profiles"
      run: |
        echo "⏳ Deploying profiles changes related to login IP ranges..."

        sf project deploy start \
            -d "$POST_STEP_PATH" \
            -o "$SCRATCH_ORG_ALIAS" \
            --ignore-conflicts \
            --ignore-warnings \
            -w 1000

        echo "✅ Profile changes are successfully deployed"