name: "Create Scratch Org"

inputs:
  devHubOrgSfdxUrl:
    description: "DevHub environment SFDX URL"
    type: string
    required: true

  configFilePath:
    description: "Relative path to a scratch org configuration file"
    type: string
    default: "config/project-scratch-def.json"

  durationInDays:
    description: "Number of days for scratch org to expire after"
    required: true
    type: choice
    default: '5'
    options:
      - 1
      - 2
      - 3
      - 5
      - 7
      - 10
      - 15
      - 20
      - 30

outputs:
  scratchOrgUrl:
    description: "Login URL of the created scratch org"
    value: ${{ steps.createScratchOrg.outputs.scratchOrgUrl }}

  scratchOrgUsername:
    description: "Username of the created scratch org"
    value: ${{ steps.createScratchOrg.outputs.scratchOrgUsername }}

  scratchOrgPassword:
    description: "Password of the created scratch org"
    value: ${{ steps.createScratchOrg.outputs.scratchOrgPassword }}

runs:
  using: "composite"

  steps:
    - name: "Authorize DevHub Org"
      shell: bash
      continue-on-error: false
      env:
        DEVHUB_ORG_SFDX_URL: ${{ inputs.devHubOrgSfdxUrl }}
        DEVHUB_ORG_ALIAS: "devHub"
      run: |
        echo "⏳ Authorizing to the DevHub environment..."

        DX_AUTH_RESPONSE=$(echo $DEVHUB_ORG_SFDX_URL | sf org login sfdx-url --sfdx-url-stdin -a "$DEVHUB_ORG_ALIAS" --json);
        DX_STATUS_CODE=$(echo $DX_AUTH_RESPONSE | jq .status);

        # early exit - error when authorizing to DevHub
        if [[ "$DX_STATUS_CODE" != "0" ]]; then

          echo "❌ Cannot log into DevHub"
          echo "$DX_AUTH_RESPONSE"
          exit 1

        fi

        echo "✅ Successfully authorized to the DevHub environment"

        # adding DevHub related details into variables to re-use in next steps
        echo "DEVHUB_ORG_ALIAS=$DEVHUB_ORG_ALIAS" >> $GITHUB_ENV