name: "Create Scratch Org"

inputs:
    devHubOrgSfdxUrl:
        description: "DevHub environment SFDX URL"
        type: string
        required: true

    durationInDays:
        description: "Number of days for scratch org to expire after"
        required: true
        type: choice
        default: '5'
        options:
            - 1
            - 2
            - 3
            - 5
            - 7
            - 10
            - 15
            - 20
            - 30

runs:
    using: "composite"

    steps:
        - shell: bash
          env:
              DEVHUB_ORG_SFDX_URL: ${{ inputs.devHubOrgSfdxUrl }}
          run: |
            echo "⏳ Authorizing to the DevHub environment..."

            DX_AUTH_RESPONSE=$(echo $DEVHUB_ORG_SFDX_URL | sf org login sfdx-url --sfdx-url-stdin --json);
            DX_STATUS_CODE=$(echo $DX_AUTH_RESPONSE | jq .status);

            # early exit - error when authorizing to DevHub
            if [[ "$DX_STATUS_CODE" != "0" ]]; then
              echo "❌ Cannot log in to DevHub"
              exit 1
            fi

            echo "✅ Successfully authorized to the DevHub environment"


            echo "⏳ Creating a scratch org..."