name: "Perform Code Analysis"

inputs:
  failWhenViolations:
    description: "Fail if violations threshold is exceeded"
    type: boolean
    default: true

  violationsThreshold:
    description: "Violations threshold"
    type: number
    default: 5

runs:
  using: "composite"

  steps:
    - name: "Debug CHILDREN Inputs"
      shell: bash
      run: |
        echo ">>> DEBUG: 'failWhenViolations': ${{ inputs.failWhenViolations }}"
        echo ">>> DEBUG: 'violationsThreshold': ${{ inputs.violationsThreshold }}"

    - name: "Install Plugin - Salesforce Code Analyzer"
      continue-on-error: false
      shell: bash
      env:
        PLUGIN_VERSION: "latest"
      run: |
        echo "⏳ Installing 'sfdx-scanner' plugin if no originally installed version is available..."

        (sf plugins | grep -i "sfdx-scanner") || (echo "y" | sf plugins install @salesforce/sfdx-scanner@$PLUGIN_VERSION)

        echo "✅ 'sfdx-scanner' plugin is installed successfully"

    - name: "Run Salesforce Code Analyzer"
      id: runCodeAnalyzer
      uses: forcedotcom/run-code-analyzer@v1
      with:
        run-command: run
        run-arguments: --normalize-severity --target . --outfile results.html
        results-artifact-name: salesforce-code-analyzer-results

    - name: "Check Analysis Results"
      shell: bash
      if: |
        inputs.failWhenViolations == 'true' &&
        (
          steps.runCodeAnalyzer.outputs.exit-code > 0 ||
          steps.runCodeAnalyzer.outputs.num-sev1-violations > 0 ||
          ${{ steps.runCodeAnalyzer.outputs.num-violations > fromJSON(inputs.violationsThreshold) }}
        )
      run: |
        echo "Failure mode enabled: ${{ inputs.failWhenViolations }}"
        echo "Defined violations threshold: ${{ inputs.violationsThreshold }}"
        echo "Reported violations: ${{ steps.runCodeAnalyzer.outputs.num-violations }}"
        echo "Analyzer exit code: ${{ steps.runCodeAnalyzer.outputs.exit-code }}"
        echo "Analyzer severity 1 violations: ${{ steps.runCodeAnalyzer.outputs.num-violations }}"

        echo "❌ Failing the step execution due to reported code analysis violations."
        exit 1