name: "Perform Code Analysis"

inputs:
  failWhenViolations:
    description: "Fail if violations threshold is exceeded"
    type: boolean
    default: true

  violationsThreshold:
    description: "Violations threshold"
    type: number
    default: 15

runs:
  using: "composite"

  steps:
    - name: "PRINT CHILD INPUTS"
      shell: bash
      run: |
        echo ">>> DEBUG: 'failWhenViolations': ${{ inputs.failWhenViolations }}"
        echo ">>> DEBUG: 'violationsThreshold': ${{ inputs.violationsThreshold }}"

    - name: "Test Separate"
      shell: bash
      if: |
        inputs.failWhenViolations == true
      run: |
        echo "✅ TEST SEPARATE STEP IS EXECUTED"

    - name: "Test Single"
      shell: bash
      if: ${{ inputs.failWhenViolations == true }}
      run: |
        echo "✅ TEST SINGLE STEP IS EXECUTED"