name: "Initialization"

inputs:
  useCache:
    description: Use cache?
    type: boolean
    default: true

runs:
  using: "composite"
    
  steps:
    - if: ${{ inputs.useCache == 'true' }}
      name: "Configure npm cache"
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          npm-${{ runner.os }}

    - name: "Print environment information"
      shell: bash
      run: |
        echo "🖥️ Operating system: $(uname -a)"
        echo "🔧 Shell: $SHELL"
        echo "🏷️ Node version: $(node --version)"
        echo "🏷️ npm version: $(npm --version)"

    - name: "Install sfdx with npm"
      shell: bash
      run: |
        echo "⏳ Installing Salesforce CLI if no originally installed version is available ..."
        npm install @salesforce/cli --global
        echo "✅ Salesforce CLI $(sf version) is installed successfully."

    - name: "Install sfdx:sfpowerkit plugin"
      shell: bash
      env:
        PLUGIN_VERSION: "latest"
        PLUGIN_PATH: "/home/runner/.local/share/sf/node_modules/sfpowerkit"
      run: |
        echo "⏳ Installing sfpowerkit plugin if no originally installed version is available ..."
        (sf plugins | grep -i "sfpowerkit") || (echo "y" | sf plugins install sfpowerkit@$PLUGIN_VERSION)

        echo "⏳ Installing missing 'rimraf' module for sfpowerkit..."

        if [ -d "$PLUGIN_PATH" ]; then

          cd "$PLUGIN_PATH"
          npm install rimraf || { echo "❌ Failed to install rimraf module."; exit 1; }
          echo "✅ 'rimraf' module installed successfully"
          cd $GITHUB_WORKSPACE

        else

          echo "❌ sfpowerkit plugin directory is not found: $PLUGIN_PATH"
          exit 1
          
        fi

        echo "✅ sfpowerkit plugin is installed successfully."

    - name: "Install sfdx:sfdmu plugin"
      shell: bash
      env:
        PLUGIN_VERSION: "latest"
      run: |
        # echo "⏳ Installing sfdmu plugin if no originally installed version is available ..."
        # (sf plugins | grep -i "sfdmu") || (echo "y" | sf plugins install sfdmu@$PLUGIN_VERSION)
        # echo "✅ sfdmu plugin is installed successfully."

    - name: "Print installed sf plugins"
      shell: bash
      run: |
        echo "⏳ Checking installed sf plugins..."
        sf plugins --core