name: "Initialization"

inputs:
  useCache:
    description: Use cache?
    type: boolean
    default: true

runs:
  using: "composite"
    
  steps:
    - if: ${{ inputs.useCache == 'true' }}
      name: "Configure npm cache"
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          npm-${{ runner.os }}

    - name: "Print node / npm versions"
      shell: bash
      run: |
        NODE_VERSION=$(node --version);
        NPM_VERSION=$(npm --version);

        echo "🏷️ Node version: $NODE_VERSION"
        echo "🏷️ npm version: $NPM_VERSION"

    - name: "Install sfdx with npm"
      shell: bash
      run: npm install @salesforce/cli --global

    - name: "Install sfdx plugins"
      shell: bash
      run: |
        # echo "⏳ Installing sfdmu plugin if no originally installed version is available ..."
        # (sf plugins | grep -i "sfdmu") || (echo "y" | sf plugins install sfdmu@$(sfdmuVersion))

        echo "⏳ Installing sfpowerkit plugin if no originally installed version is available ..."
        (sf plugins | grep -i "sfpowerkit") || (echo "y" | sf plugins install sfpowerkit@$latest)

        echo ">> Checking sf plugins..."
        sf plugins --core

        echo ">> Checking if 'rimraf' is installed..."
        npm list -g rimraf

        echo ">> Trying to re-install 'rimraf'..."
        CURRENT_PATH=$(pwd)
        cd /home/runner/.local/share/sf/node_modules/sfpowerkit
        npm install rimraf
        cd $CURRENT_PATH

        echo ">> Checking if directory exists..."
        ls /home/runner/.local/share/sf/node_modules/sfpowerkit/node_modules -l

        echo ">> Checking 'sfpowerkit' version..."
        sf sfpowerkit --version
        sf sfpowerkit:auth:login