name: "Create Scratch Org"
run-name: "Create Scratch Org (${{ github.actor }})"

on:
    workflow_dispatch:
        inputs:
            durationInDays:
                description: "Number of days for scratch org to expire after"
                required: true
                type: choice
                default: '5'
                options:
                    - 1
                    - 2
                    - 3
                    - 5
                    - 7
                    - 10
                    - 15
                    - 20
                    - 30

jobs:
    Job_CreateScratchOrg:
        runs-on: ubuntu-latest
        
        name: "Create Scratch Org"

        steps:
            - name: "Test Step #1"
              run: echo "Selected number of duration in days - ${{ inputs.durationInDays }}"

            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Initialize"
              uses: ./.github/actions/init

            - name: "Print files"
              run: ls -l