name: "Deploy Metadata Manual"
run-name: "Deploy Metadata Manual (${{ github.actor }})"

on:
  workflow_dispatch:
    inputs:
      targetOrgUrl:
        description: "Target environment login URL"
        type: string
        default: "https://login.salesforce.com"

      targetOrgUsername: 
        description: "Target environment username"
        type: string
        default: "none"

      targetOrgPassword:
        description: "Target environment password"
        type: string
        default: "none"

      shouldCreateScratchOrg:
        description: "Create new scratch org?"
        type: boolean
        default: false

      scratchOrgDurationInDays:
        description: "Number of days for scratch org to expire after"
        required: true
        type: choice
        default: '5'
        options:
          - 1
          - 2
          - 3
          - 5
          - 7
          - 10
          - 15
          - 20
          - 30

      deploymentMode:
        description: "Deployment mode"
        required: true
        type: choice
        default: "install"
        options:
          - install
          - upgrade
          - validateOnly
          - validateWithTests

jobs:
  DeployMetadata:
    runs-on: ubuntu-latest
      
    name: "Deploy Metadata"

    env:
      TARGET_ORG_URL: ${{ inputs.targetOrgUrl }}
      TARGET_ORG_USERNAME: ${{ inputs.targetOrgUsername }}
      TARGET_ORG_PASSWORD: ${{ inputs.targetOrgPassword }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Initialize"
        uses: ./.github/actions/init

      - if: ${{ inputs.shouldCreateScratchOrg == true }}
        name: "Create Scratch Org"
        id: createScratchOrg
        uses: ./.github/actions/createScratchOrg
        with:
          devHubOrgSfdxUrl: ${{ secrets.DEVHUB_ORG_SFDX_URL }}
          durationInDays: ${{ inputs.scratchOrgDurationInDays }}

      - name: "Assign Target Org Credentials"
        run: |
          if [[ "${{ inputs.shouldCreateScratchOrg }}" =~ ^[Tt]rue$ ]] ; then

            echo "TARGET_ORG_URL=${{ steps.createScratchOrg.outputs.scratchOrgUrl }}" >> $GITHUB_ENV
            echo "TARGET_ORG_USERNAME=${{ steps.createScratchOrg.outputs.scratchOrgUsername }}" >> $GITHUB_ENV
            echo "TARGET_ORG_PASSWORD=${{ steps.createScratchOrg.outputs.scratchOrgPassword }}" >> $GITHUB_ENV

          fi

      - name: "Deploy Metadata"
        uses: ./.github/actions/deployMetadata
        with:
          targetOrgUrl: ${{ env.TARGET_ORG_URL }}
          targetOrgUsername: ${{ env.TARGET_ORG_USERNAME }}
          targetOrgPassword: ${{ env.TARGET_ORG_PASSWORD }}
          deploymentMode: ${{ inputs.deploymentMode }}