name: "Validate Pull Request"
run-name: "Validate Pull Request (${{ github.actor }})"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      failWhenAnalysingCode:
        description: "Fail when running code analysis?"
        type: boolean
        default: true

      failWhenAnalysingFlows:
        description: "Fail when running flows analysis?"
        type: boolean
        default: true

jobs:
  PerformCodeAnalysis:
    runs-on: ubuntu-latest
    
    name: "Perform Code Analysis"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      
      - name: "Initialize"
        uses: ./.github/actions/init

      - name: "Perform Flows Analysis"
        uses: ./.github/actions/performFlowsAnalysis
        with:
          failWhenViolations: ${{ github.event_name == 'workflow_dispatch' && !inputs.failWhenAnalysingFlows && 'false' || 'true' }}