name: "Validate Pull Request"
run-name: "Validate Pull Request (${{ github.actor }})"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      failWhenAnalysingCode:
        description: "Fail when running code analysis?"
        type: boolean
        default: true

      testString:
        description: "Test string param"
        type: string

jobs:
  PerformCodeAnalysis:
    runs-on: ubuntu-latest
    
    name: "Perform Code Analysis"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "PRINT PARENT INPUTS"
        run: |
          echo ">>> DEBUG: 'failWhenAnalysingCode': ${{ inputs.failWhenAnalysingCode }}"
          echo ">>> DEBUG: 'testString': ${{ inputs.testString }}"

      - name: "Perform Code Analysis"
        uses: ./.github/actions/performCodeAnalysis
        with:
          testString: ${{ inputs.testString || 'Alternative value' }}
          failWhenViolations: ${{ inputs.failWhenAnalysingCode || true }}